root_folder : N:/SCI-NBI-Cleanroom/NQCP/SC-platform
attributes : 
  - Initials : DSDK
  - SubjectID : A001B001
keywords : [] # Optional
skip : [] # Optional
folders:
  - "1_Resonators/$SubjectID/0_Design/"
  - "1_Resonators/$SubjectID/1_Exposure/"
  - "1_Resonators/$SubjectID/2_OpticalImages/0_Cleaning/"
  - "1_Resonators/$SubjectID/2_OpticalImages/1_Development/"
  - "1_Resonators/$SubjectID/2_OpticalImages/2_Etch/1_PostEtch/"
  - "1_Resonators/$SubjectID/2_OpticalImages/2_Etch/2_PostStrip/"